---
- hosts: kafkavm

  tasks:
  - debug:
      msg:  "# ===== Starting Kafka installation ... ===== #"

  - name: Install Java8
    apt:
      name: openjdk-8-jre-headless
    become: true

  - name: Create Kafka dir
    file: 
      path: /home/ubuntu/kafka_download/
      state: directory

  - name: Create Kafka source dir
    file: 
      path: /home/ubuntu/kafka_download/kafka/
      state: directory

  - name: Download Kafka 'tar' file
    get_url:
      url: http://apache.crihan.fr/dist/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz
      dest: /home/ubuntu/kafka_download/

  - name: Extract files from kafka archive
    unarchive: 
      src: /home/ubuntu/kafka_download/kafka_2.11-0.11.0.1.tgz
      dest: /home/ubuntu/kafka_download/kafka
      remote_src: yes

  - name: Start Zookeeper
    shell: "(/home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/bin/zookeeper-server-start.sh /home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/config/zookeeper.properties >/dev/null 2>&1 &)"
    async: 10
    poll: 0

  - name: Start Kafka server
    shell: "(/home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/bin/kafka-server-start.sh /home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/config/server.properties >/dev/null 2>&1 &)"
    async: 10
    poll: 0

  - name: Create a Kafka topic
    shell: "(/home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test)"

  - name: List all kafka topics
    shell: "(/home/ubuntu/kafka_download/kafka/kafka_2.11-0.11.0.1/bin/kafka-topics.sh --list --zookeeper localhost:2181 > /tmp/kafka_topics 2>&1)"